[package]
name = "rust_download_stream"
version = "0.1.0"
edition = "2024"

[dependencies]
futures-util = "0.3.31"
indicatif = "0.17.11"
redirect = "0.3.0"
reqwest = { version = "0.12.15", features = ["stream"] }
tokio = { version = "1.44.2", features = ["full"] }
